general.import = [
"~/.config/alacritty/themes/themes/dark_solarized.toml",
]

[font]
size = 12.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]

family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

