tap "argoproj/tap"
tap "blacktop/tap"
tap "hack-different/jailbreak"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "argo"
brew "asio"
brew "xz"
brew "awscli"
brew "bash"
brew "bettercap"
brew "harfbuzz"
brew "p7zip"
brew "binwalk"
brew "cabextract"
brew "ccache"
brew "cmake"
brew "dfu-util"
brew "exiftool"
brew "fd"
brew "ffuf"
brew "fzf"
brew "git-lfs"
brew "gnupg"
brew "gobject-introspection"
brew "gum"
brew "hashcat"
brew "helm"
brew "hugo"
brew "irssi"
brew "john-jumbo"
brew "jq"
brew "kubernetes-cli"
brew "lazygit"
brew "lftp"
brew "libewf"
brew "mas"
brew "minikube"
brew "mupdf"
brew "neovim"
brew "ninja"
brew "nmap"
brew "node"
brew "pipx"
brew "python@3.8"
brew "qemu"
brew "rbenv"
brew "ripgrep"
brew "shellcheck"
brew "sphinx-doc"
brew "terraform"
brew "terraform-inventory"
brew "tmux"
brew "tree"
brew "upx"
brew "wget"
brew "xclip"
brew "xcodes"
brew "yara"
brew "yarn"
brew "blacktop/tap/ipsw"
cask "adoptopenjdk"
cask "alacritty"
cask "burp-suite"
cask "codeql"
cask "font-agave-nerd-font"
cask "font-ubuntu-mono-nerd-font"
cask "ghidra"
cask "hashicorp-vagrant"
cask "hex-fiend"
cask "idafree"
cask "mattermost"
cask "osquery"
cask "phantomjs"
cask "temurin"
mas "1Password for Safari", id: 1569813296
mas "Developer", id: 640199958
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "Goodnotes", id: 1444383602
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Save to Pocket", id: 1477385213
mas "Save to Raindrop.io", id: 1549370672
mas "Slack", id: 803453959
mas "Structured", id: 1499198946
mas "Swipes", id: 1008187030
mas "The Unarchiver", id: 425424353
mas "TickTick", id: 966085870
mas "TweetDeck", id: 485812721
mas "uBlock", id: 1385985095
mas "Xcode", id: 497799835
mas "Xmind", id: 1327661892
mas "YubiKey Personalization Tool", id: 638161122
vscode "cschlosser.doxdocgen"
vscode "github.vscode-codeql"
vscode "hbenl.vscode-test-explorer"
vscode "jeff-hykin.better-cpp-syntax"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.test-adapter-converter"
vscode "twxs.cmake"
